#!/usr/bin/env node
// IluBoard CLI, single file — generated by tools/bundle.mjs from IluBoard v0.1.0 — do not edit.
// Source: https://github.com/ilumetric/IluBoard (tools/iluboard.mjs + src/core/*). Regenerate: npm run bundle
// Usage: node iluboard.mjs --help   (Node 20+, no dependencies)
// Modules: src/core/version.js, src/core/model.js, src/core/text.js, src/core/diff.js, tools/iluboard.mjs

import * as __node_child_process from 'node:child_process';
import * as __node_fs from 'node:fs';
import * as __node_path from 'node:path';

// ---- src/core/version.js -----------------------------------------------------
const __iluboard_src_core_version = (() => {
// App version (also printed by the CLI; tools/bundle.mjs reads it from here).
const APP_VERSION = '0.1.0';
return {
  APP_VERSION,
};
})();

// ---- src/core/model.js -------------------------------------------------------
const __iluboard_src_core_model = (() => {
// board.json: constants, normalisation, validation, canonical serialisation and
// the few edits both the browser and the CLI make (move, add, set).
// Pure ES module: no DOM, no Node APIs, no dependencies.

const FORMAT = 'iluboard';
const VERSION = 1;
const DEFAULT_COLUMNS = ['idea', 'todo', 'doing', 'done', 'dropped'];
const PRIORITIES = ['P0', 'P1', 'P2', 'P3'];
const SIZES = ['S', 'M', 'L', 'XL'];
const UPDATED_BY = ['human', 'agent'];
/** Columns whose cards must say when they are done. */
const NEEDS_DONE_WHEN = ['todo', 'doing'];
/** Columns whose cards are finished (no overdue warnings). */
const CLOSED_COLUMNS = ['done', 'dropped'];

const TOP_KEYS = ['format', 'version', 'meta', 'columns', 'cards'];
const META_KEYS = ['title', 'id_prefix', 'updated'];
const CARD_KEYS = ['id', 'title', 'column', 'order', 'priority', 'size', 'owner', 'goal', 'done_when', 'notes', 'tags', 'due', 'updated', 'updated_by'];
/** Card fields a person or agent edits as text (everything but id / column / order / bookkeeping). */
const EDITABLE_KEYS = ['title', 'priority', 'size', 'owner', 'goal', 'done_when', 'notes', 'tags', 'due'];

const ID_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]*$/;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

const isObj = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const clone = (v) => (v === undefined ? v : JSON.parse(JSON.stringify(v)));

/** Local calendar date as YYYY-MM-DD. */
function today(d = new Date()) {
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function isDate(s) {
  if (typeof s !== 'string' || !DATE_RE.test(s)) return false;
  const [y, m, d] = s.split('-').map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d));
  return dt.getUTCFullYear() === y && dt.getUTCMonth() === m - 1 && dt.getUTCDate() === d;
}

/** A fresh board. */
function emptyBoard(title = 'Board', date = today()) {
  return { format: FORMAT, version: VERSION, meta: { title, updated: date }, columns: [...DEFAULT_COLUMNS], cards: [] };
}

/** JSON.parse with the line and column of a syntax error in the message. */
function parse(text) {
  const src = String(text).replace(/^﻿/, '');
  try {
    return JSON.parse(src);
  } catch (e) {
    const m = String(e.message).match(/position (\d+)/);
    if (m) {
      const before = src.slice(0, Number(m[1]));
      const line = before.split('\n').length;
      const col = before.length - before.lastIndexOf('\n');
      throw new SyntaxError(`invalid JSON at line ${line}, column ${col}: ${e.message}`);
    }
    throw new SyntaxError(`invalid JSON: ${e.message}`);
  }
}

/**
 * A board object from text or an object (deep copy). Fills in a missing
 * `meta`, `columns` or `cards` so the rest of the code can rely on them; it
 * never "fixes" wrong values — `validate` reports those.
 */
function normalize(input) {
  const doc = typeof input === 'string' ? parse(input) : clone(input);
  if (!isObj(doc)) throw new TypeError('board must be a JSON object');
  if (doc.meta === undefined) doc.meta = {};
  if (doc.columns === undefined) doc.columns = [...DEFAULT_COLUMNS];
  if (doc.cards === undefined) doc.cards = [];
  return doc;
}

// ---- validation ------------------------------------------------------------

/** Issue texts by code, English and Russian. `{x}` is replaced from params. */
const MESSAGES = {
  en: {
    not_object: 'the board must be a JSON object',
    format: 'format must be "iluboard"',
    version: 'unsupported version {value} (this tool reads version 1)',
    meta: 'meta must be an object',
    meta_string: 'meta.{key} must be a string',
    columns: 'columns must be a non-empty array of strings',
    column_dup: 'column "{value}" is listed twice',
    cards: 'cards must be an array',
    card: 'a card must be an object',
    id_missing: 'card has no id',
    id_format: 'id "{value}" may only contain letters, digits, "_", "." and "-"',
    id_dup: 'id "{value}" is used by more than one card',
    title_missing: 'card {id} has no title',
    column_missing: 'card {id} has no column',
    column_unknown: 'card {id}: column "{value}" is not in columns',
    order: 'card {id}: order must be a whole number ≥ 0',
    priority: 'card {id}: priority must be one of P0, P1, P2, P3',
    size: 'card {id}: size must be one of S, M, L, XL',
    updated_by: 'card {id}: updated_by must be "human" or "agent"',
    string: 'card {id}: {key} must be a string',
    date: '{where}{key} must be a date YYYY-MM-DD (got "{value}")',
    tags: 'card {id}: tags must be an array of strings',
    done_when: 'card {id} is in "{value}" but has no done_when (required for todo and doing)',
    unknown_field: 'card {id}: unknown field "{key}" (kept as is; custom fields should start with x_)',
    unknown_top: 'unknown top-level field "{key}" (kept as is; custom fields should start with x_)',
    unknown_meta: 'unknown field meta.{key} (kept as is; custom fields should start with x_)',
  },
  ru: {
    not_object: 'доска должна быть JSON-объектом',
    format: 'format должен быть "iluboard"',
    version: 'неподдерживаемая версия {value} (поддерживается версия 1)',
    meta: 'meta должна быть объектом',
    meta_string: 'meta.{key} должно быть строкой',
    columns: 'columns — непустой массив строк',
    column_dup: 'колонка "{value}" указана дважды',
    cards: 'cards должен быть массивом',
    card: 'карточка должна быть объектом',
    id_missing: 'у карточки нет id',
    id_format: 'id "{value}": допустимы буквы, цифры, "_", "." и "-"',
    id_dup: 'id "{value}" встречается у нескольких карточек',
    title_missing: 'у карточки {id} нет title',
    column_missing: 'у карточки {id} нет column',
    column_unknown: 'карточка {id}: колонки "{value}" нет в columns',
    order: 'карточка {id}: order — целое число ≥ 0',
    priority: 'карточка {id}: priority — одно из P0, P1, P2, P3',
    size: 'карточка {id}: size — одно из S, M, L, XL',
    updated_by: 'карточка {id}: updated_by — "human" или "agent"',
    string: 'карточка {id}: {key} должно быть строкой',
    date: '{where}{key} — дата в формате ГГГГ-ММ-ДД (сейчас "{value}")',
    tags: 'карточка {id}: tags — массив строк',
    done_when: 'карточка {id} в колонке "{value}", но без done_when (обязателен для todo и doing)',
    unknown_field: 'карточка {id}: неизвестное поле "{key}" (сохранено как есть; свои поля — с префиксом x_)',
    unknown_top: 'неизвестное поле верхнего уровня "{key}" (сохранено; свои поля — с префиксом x_)',
    unknown_meta: 'неизвестное поле meta.{key} (сохранено; свои поля — с префиксом x_)',
  },
};

function issueText(issue, lang = 'en') {
  const table = MESSAGES[lang] || MESSAGES.en;
  const tpl = table[issue.code] || MESSAGES.en[issue.code] || issue.code;
  return tpl.replace(/\{(\w+)\}/g, (_, k) => (issue[k] === undefined ? '' : String(issue[k])));
}

/**
 * Check a board. Returns { ok, errors, warnings }; each issue is
 * { code, path, ...params } — turn it into text with issueText(issue, lang).
 * Errors make `ok` false; warnings (unknown fields) do not.
 */
function validate(doc) {
  const errors = [];
  const warnings = [];
  const err = (code, path, params = {}) => errors.push({ code, path, ...params });
  const warn = (code, path, params = {}) => warnings.push({ code, path, ...params });

  if (!isObj(doc)) {
    err('not_object', '');
    return { ok: false, errors, warnings };
  }
  if (doc.format !== FORMAT) err('format', 'format', { value: doc.format });
  if (doc.version !== VERSION) err('version', 'version', { value: JSON.stringify(doc.version) });
  for (const k of Object.keys(doc)) if (!TOP_KEYS.includes(k) && !k.startsWith('x_')) warn('unknown_top', k, { key: k });

  if (doc.meta !== undefined && !isObj(doc.meta)) err('meta', 'meta');
  else if (doc.meta) {
    for (const k of ['title', 'id_prefix']) {
      if (doc.meta[k] !== undefined && typeof doc.meta[k] !== 'string') err('meta_string', `meta.${k}`, { key: k });
    }
    if (doc.meta.updated !== undefined && !isDate(doc.meta.updated)) err('date', 'meta.updated', { where: 'meta.', key: 'updated', value: doc.meta.updated });
    for (const k of Object.keys(doc.meta)) if (!META_KEYS.includes(k) && !k.startsWith('x_')) warn('unknown_meta', `meta.${k}`, { key: k });
  }

  let columns = [];
  if (!Array.isArray(doc.columns) || !doc.columns.length || doc.columns.some((c) => typeof c !== 'string' || !c)) {
    err('columns', 'columns');
  } else {
    columns = doc.columns;
    const seen = new Set();
    for (const c of columns) {
      if (seen.has(c)) err('column_dup', 'columns', { value: c });
      seen.add(c);
    }
  }

  if (!Array.isArray(doc.cards)) {
    err('cards', 'cards');
    return { ok: errors.length === 0, errors, warnings };
  }
  const ids = new Map();
  doc.cards.forEach((c, i) => {
    const p = `cards[${i}]`;
    if (!isObj(c)) { err('card', p); return; }
    const id = typeof c.id === 'string' && c.id ? c.id : `#${i}`;
    if (typeof c.id !== 'string' || !c.id) err('id_missing', `${p}.id`, { id });
    else if (!ID_RE.test(c.id)) err('id_format', `${p}.id`, { id, value: c.id });
    else ids.set(c.id, (ids.get(c.id) || 0) + 1);

    if (typeof c.title !== 'string' || !c.title.trim()) err('title_missing', `${p}.title`, { id });
    if (c.column === undefined) err('column_missing', `${p}.column`, { id });
    else if (columns.length && !columns.includes(c.column)) err('column_unknown', `${p}.column`, { id, value: c.column });
    if (c.order !== undefined && !(Number.isInteger(c.order) && c.order >= 0)) err('order', `${p}.order`, { id });
    if (c.priority !== undefined && !PRIORITIES.includes(c.priority)) err('priority', `${p}.priority`, { id });
    if (c.size !== undefined && !SIZES.includes(c.size)) err('size', `${p}.size`, { id });
    if (c.updated_by !== undefined && !UPDATED_BY.includes(c.updated_by)) err('updated_by', `${p}.updated_by`, { id });
    for (const k of ['owner', 'goal', 'done_when', 'notes']) {
      if (c[k] !== undefined && typeof c[k] !== 'string') err('string', `${p}.${k}`, { id, key: k });
    }
    for (const k of ['due', 'updated']) {
      if (c[k] !== undefined && !isDate(c[k])) err('date', `${p}.${k}`, { where: `${id}: `, key: k, value: c[k] });
    }
    if (c.tags !== undefined && (!Array.isArray(c.tags) || c.tags.some((t) => typeof t !== 'string'))) err('tags', `${p}.tags`, { id });
    if (NEEDS_DONE_WHEN.includes(c.column) && !(typeof c.done_when === 'string' && c.done_when.trim())) {
      err('done_when', `${p}.done_when`, { id, value: c.column });
    }
    for (const k of Object.keys(c)) if (!CARD_KEYS.includes(k) && !k.startsWith('x_')) warn('unknown_field', `${p}.${k}`, { id, key: k });
  });
  for (const [id, n] of ids) if (n > 1) err('id_dup', 'cards', { id, value: id });

  return { ok: errors.length === 0, errors, warnings };
}

// ---- canonical form ----------------------------------------------------------

const empty = (v) => v === undefined || v === null || v === '' || (Array.isArray(v) && v.length === 0);

/** Known keys in their fixed order, then the rest (x_ and unknown) in their original order. */
function orderKeys(obj, known, dropEmpty) {
  const out = {};
  for (const k of known) if (k in obj && !(dropEmpty && empty(obj[k]))) out[k] = obj[k];
  for (const k of Object.keys(obj)) if (!known.includes(k) && obj[k] !== undefined) out[k] = obj[k];
  return out;
}

/**
 * The canonical board: stable key order, empty optional fields dropped, cards
 * sorted by column (in `columns` order) then `order`, and `order` renumbered
 * 0, 1, 2… inside each column. Returns a new object.
 */
function canonical(input) {
  const doc = normalize(input);
  const columns = Array.isArray(doc.columns) ? doc.columns : [];
  let cards = Array.isArray(doc.cards) ? doc.cards : doc.cards;
  if (Array.isArray(cards)) {
    const colIndex = (c) => {
      const i = columns.indexOf(c?.column);
      return i < 0 ? columns.length : i;
    };
    const ord = (c) => (Number.isFinite(c?.order) ? c.order : Number.MAX_SAFE_INTEGER);
    cards = cards
      .map((c, i) => ({ c, i }))
      .sort((a, b) => colIndex(a.c) - colIndex(b.c)
        || (colIndex(a.c) === columns.length ? String(a.c?.column).localeCompare(String(b.c?.column)) : 0)
        || ord(a.c) - ord(b.c)
        || a.i - b.i)
      .map(({ c }) => c);
    const counters = new Map();
    cards = cards.map((c) => {
      if (!isObj(c)) return c;
      const n = counters.get(c.column) || 0;
      counters.set(c.column, n + 1);
      if (typeof c.title === 'string') c.title = c.title.trim();
      if (Array.isArray(c.tags)) c.tags = c.tags.filter((t) => !(typeof t === 'string' && !t.trim()));
      return orderKeys({ ...c, order: n }, CARD_KEYS, true);
    });
  }
  const out = orderKeys({ ...doc, cards }, TOP_KEYS, false);
  if (isObj(out.meta)) out.meta = orderKeys(out.meta, META_KEYS, true);
  return out;
}

const isPrimitive = (v) => v === null || typeof v !== 'object';

/** JSON text of a value; arrays of primitives stay on one line. */
function fmtValue(v, indent) {
  if (isPrimitive(v)) return JSON.stringify(v);
  const pad = '  '.repeat(indent + 1);
  const end = '  '.repeat(indent);
  if (Array.isArray(v)) {
    if (!v.length) return '[]';
    if (v.every(isPrimitive)) return `[${v.map((x) => JSON.stringify(x)).join(', ')}]`;
    return `[\n${v.map((x) => pad + fmtValue(x, indent + 1)).join(',\n')}\n${end}]`;
  }
  const keys = Object.keys(v).filter((k) => v[k] !== undefined);
  if (!keys.length) return '{}';
  return `{\n${keys.map((k) => `${pad}${JSON.stringify(k)}: ${fmtValue(v[k], indent + 1)}`).join(',\n')}\n${end}}`;
}

/** The board as canonical text: one field per line, trailing newline. */
function serialize(doc) {
  return `${fmtValue(canonical(doc), 0)}\n`;
}

// ---- queries and edits ---------------------------------------------------------

const findCard = (doc, id) => doc.cards.find((c) => c && c.id === id) || null;

/** Cards of one column in board order. */
function cardsIn(doc, column) {
  return doc.cards
    .map((c, i) => ({ c, i }))
    .filter(({ c }) => c && c.column === column)
    .sort((a, b) => (a.c.order ?? Infinity) - (b.c.order ?? Infinity) || a.i - b.i)
    .map(({ c }) => c);
}

/** Renumber `order` 0, 1, 2… for the given cards (already in the wanted order). */
function renumber(list) {
  list.forEach((c, i) => { c.order = i; });
}

/** Mark a card as changed now by `by` ('human' | 'agent'). */
function touch(card, by, date = today()) {
  card.updated = date;
  card.updated_by = by;
}

/**
 * The prefix of new ids: meta.id_prefix, else the most common letter prefix of
 * the existing ids, else "B".
 */
function idPrefix(doc) {
  if (typeof doc.meta?.id_prefix === 'string' && doc.meta.id_prefix) return doc.meta.id_prefix;
  const count = new Map();
  for (const c of doc.cards) {
    const m = typeof c?.id === 'string' && c.id.match(/^(.*?)(\d+)$/);
    if (m && m[1]) count.set(m[1], (count.get(m[1]) || 0) + 1);
  }
  let best = 'B';
  let n = 0;
  for (const [p, k] of count) if (k > n) { best = p; n = k; }
  return best;
}

/** Next free id with a prefix: prefix + (largest number used with it + 1). */
function nextId(doc, prefix = idPrefix(doc)) {
  const esc = prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`^${esc}(\\d+)$`);
  let max = 0;
  for (const c of doc.cards) {
    const m = typeof c?.id === 'string' && c.id.match(re);
    if (m) max = Math.max(max, Number(m[1]));
  }
  let n = max + 1;
  while (findCard(doc, `${prefix}${n}`)) n++;
  return `${prefix}${n}`;
}

/**
 * Move a card to `column` at `index` (0 = top; omitted or out of range = bottom).
 * Renumbers both columns. Marks the card touched when its column or position changed.
 * Returns the card; throws when the card or column does not exist.
 */
function moveCard(doc, id, column, index, { by = 'human', date = today() } = {}) {
  const card = findCard(doc, id);
  if (!card) throw new Error(`no card "${id}"`);
  if (!doc.columns.includes(column)) throw new Error(`no column "${column}" (columns: ${doc.columns.join(', ')})`);
  const from = card.column;
  const before = cardsIn(doc, column).indexOf(card);
  const source = cardsIn(doc, from).filter((c) => c !== card);
  const target = from === column ? source : cardsIn(doc, column);
  const at = index === undefined || index === null || index < 0 || index > target.length ? target.length : index;
  target.splice(at, 0, card);
  card.column = column;
  if (from !== column) renumber(source);
  renumber(target);
  if (from !== column || before !== at) touch(card, by, date);
  return card;
}

/** Clean a user-supplied field value; '' / [] mean "remove the field". */
function cleanField(key, value) {
  if (key === 'tags') {
    const list = Array.isArray(value) ? value : String(value ?? '').split(',');
    return list.map((t) => String(t).trim()).filter(Boolean);
  }
  if (value === undefined || value === null) return undefined;
  return typeof value === 'string' ? value.trim() : value;
}

/**
 * Set fields of a card; an empty value removes the field. Marks the card
 * touched when anything changed. Returns the list of changed keys.
 */
function setFields(doc, id, fields, { by = 'human', date = today() } = {}) {
  const card = findCard(doc, id);
  if (!card) throw new Error(`no card "${id}"`);
  const changed = [];
  for (const [key, raw] of Object.entries(fields)) {
    if (key === 'id' || key === 'column' || key === 'order' || key === 'updated' || key === 'updated_by') continue;
    const value = cleanField(key, raw);
    const before = JSON.stringify(card[key]);
    if (empty(value)) delete card[key];
    else card[key] = value;
    if (JSON.stringify(card[key]) !== before) changed.push(key);
  }
  if (changed.length) touch(card, by, date);
  return changed;
}

/**
 * Add a card. `fields.id` is optional (nextId); `fields.column` defaults to the
 * first column; the card goes to the bottom of its column unless `index` is given.
 */
function addCard(doc, fields, { by = 'human', date = today(), index } = {}) {
  const id = fields.id ? String(fields.id).trim() : nextId(doc);
  if (!ID_RE.test(id)) throw new Error(`bad id "${id}" (letters, digits, "_", "." and "-")`);
  if (findCard(doc, id)) throw new Error(`id "${id}" is already used`);
  const column = fields.column || doc.columns[0];
  if (!doc.columns.includes(column)) throw new Error(`no column "${column}" (columns: ${doc.columns.join(', ')})`);
  const card = { id, title: '', column, order: cardsIn(doc, column).length };
  for (const [k, v] of Object.entries(fields)) {
    if (k === 'id' || k === 'column' || k === 'order') continue;
    const value = cleanField(k, v);
    if (!empty(value)) card[k] = value;
  }
  touch(card, by, date);
  doc.cards.push(card);
  if (index !== undefined && index !== null) moveCard(doc, id, column, index, { by, date });
  return card;
}

/** Remove a card; renumbers its column. Returns the removed card. */
function removeCard(doc, id) {
  const card = findCard(doc, id);
  if (!card) throw new Error(`no card "${id}"`);
  doc.cards.splice(doc.cards.indexOf(card), 1);
  renumber(cardsIn(doc, card.column));
  return card;
}
return {
  FORMAT,
  VERSION,
  DEFAULT_COLUMNS,
  PRIORITIES,
  SIZES,
  UPDATED_BY,
  NEEDS_DONE_WHEN,
  CLOSED_COLUMNS,
  TOP_KEYS,
  META_KEYS,
  CARD_KEYS,
  EDITABLE_KEYS,
  ID_RE,
  today,
  isDate,
  emptyBoard,
  parse,
  normalize,
  MESSAGES,
  issueText,
  validate,
  canonical,
  serialize,
  findCard,
  cardsIn,
  touch,
  idPrefix,
  nextId,
  moveCard,
  setFields,
  addCard,
  removeCard,
};
})();

// ---- src/core/text.js --------------------------------------------------------
const __iluboard_src_core_text = (() => {
const { CLOSED_COLUMNS, cardsIn } = __iluboard_src_core_model;
// The board in words: `text` (one line per card, for agents) and `md`
// (Markdown tables, e.g. for backlog.md). Pure module.


const COLUMN_LABELS = {
  ru: { idea: 'идея', todo: 'к работе', doing: 'в работе', done: 'готово', dropped: 'отменено' },
  en: { idea: 'idea', todo: 'to do', doing: 'doing', done: 'done', dropped: 'dropped' },
};

const WORDS = {
  ru: {
    due: 'до', cards: (n) => `${n} ${plural(n, 'карточка', 'карточки', 'карточек')}`, updated: 'обновлено',
    empty: '(пусто)', goal: 'веха', doneWhen: 'готово, когда', notes: 'заметки', tags: 'теги', by: 'правка',
    task: 'Задача', size: 'Размер', owner: 'Кто', due2: 'Срок', exported: 'Экспорт', noEdit: 'не править руками',
  },
  en: {
    due: 'due', cards: (n) => `${n} card${n === 1 ? '' : 's'}`, updated: 'updated',
    empty: '(empty)', goal: 'goal', doneWhen: 'done when', notes: 'notes', tags: 'tags', by: 'last edit',
    task: 'Task', size: 'Size', owner: 'Owner', due2: 'Due', exported: 'Exported', noEdit: 'do not edit by hand',
  },
};

function plural(n, one, few, many) {
  const a = Math.abs(n) % 100;
  const b = a % 10;
  if (a > 10 && a < 20) return many;
  if (b === 1) return one;
  if (b >= 2 && b <= 4) return few;
  return many;
}

const words = (lang) => WORDS[lang] || WORDS.en;
const columnLabel = (column, lang = 'ru') => (COLUMN_LABELS[lang] || COLUMN_LABELS.en)[column] || column;

/** "B8 [P0/M] max — Title (до 2026-10-12)" */
function cardLine(card, lang = 'ru') {
  const tag = [card.priority, card.size].filter(Boolean).join('/');
  let s = card.id;
  if (tag) s += ` [${tag}]`;
  if (card.owner) s += ` ${card.owner}`;
  s += ` — ${card.title || ''}`;
  if (card.due) s += ` (${words(lang).due} ${card.due})`;
  return s;
}

/** Keep the requested columns (all when none are given), in board order. */
function pickColumns(doc, only) {
  if (!only || !only.length) return doc.columns;
  return doc.columns.filter((c) => only.includes(c));
}

/**
 * The board as text: a header line, then per column a "## label (id) — n" line
 * and one line per card. `full` adds goal / done_when / notes / tags below each card.
 */
function boardText(doc, { lang = 'ru', full = false, columns } = {}) {
  const w = words(lang);
  const out = [];
  const title = doc.meta?.title || 'Board';
  const upd = doc.meta?.updated ? `, ${w.updated} ${doc.meta.updated}` : '';
  out.push(`# ${title} — ${w.cards(doc.cards.length)}${upd}`);
  for (const col of pickColumns(doc, columns)) {
    const list = cardsIn(doc, col);
    out.push('', `## ${columnLabel(col, lang)} (${col}) — ${list.length}`);
    if (!list.length) out.push(w.empty);
    for (const c of list) {
      out.push(`- ${cardLine(c, lang)}`);
      if (!full) continue;
      const extra = [];
      if (c.goal) extra.push(`${w.goal}: ${c.goal}`);
      if (c.done_when) extra.push(`${w.doneWhen}: ${c.done_when}`);
      if (c.notes) extra.push(`${w.notes}: ${c.notes.replace(/\s*\n\s*/g, ' / ')}`);
      if (c.tags?.length) extra.push(`${w.tags}: ${c.tags.join(', ')}`);
      if (c.updated) extra.push(`${w.by}: ${c.updated}${c.updated_by ? ` ${c.updated_by}` : ''}`);
      for (const e of extra) out.push(`  ${e}`);
    }
  }
  return `${out.join('\n')}\n`;
}

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s*\n\s*/g, '<br>');

/**
 * Markdown export: a title, a generated-file note, and a table per column
 * (id · task · P · size · owner · goal · done when · due).
 */
function boardMarkdown(doc, { lang = 'ru', columns, source = 'board.json' } = {}) {
  const w = words(lang);
  const out = [];
  out.push(`# ${doc.meta?.title || 'Board'}`);
  out.push('');
  out.push(`> ${w.exported}: \`${source}\`${doc.meta?.updated ? ` · ${w.updated} ${doc.meta.updated}` : ''} · ${w.noEdit} (\`node iluboard.mjs md ${source}\`)`);
  for (const col of pickColumns(doc, columns)) {
    const list = cardsIn(doc, col);
    out.push('', `## ${capital(columnLabel(col, lang))} · ${list.length}`, '');
    if (!list.length) { out.push(`_${w.empty}_`); continue; }
    const closed = CLOSED_COLUMNS.includes(col);
    out.push(`| id | ${w.task} | P | ${w.size} | ${w.owner} | ${capital(w.goal)} | ${capital(w.doneWhen)} | ${w.due2} |`);
    out.push('|---|---|---|---|---|---|---|---|');
    for (const c of list) {
      const title = closed && col === 'dropped' ? `~~${cell(c.title)}~~` : cell(c.title);
      out.push(`| ${cell(c.id)} | ${title} | ${cell(c.priority)} | ${cell(c.size)} | ${cell(c.owner)} | ${cell(c.goal)} | ${cell(c.done_when)} | ${cell(c.due)} |`);
    }
  }
  return `${out.join('\n')}\n`;
}

const capital = (s) => s.charAt(0).toUpperCase() + s.slice(1);
return {
  COLUMN_LABELS,
  plural,
  words,
  columnLabel,
  cardLine,
  boardText,
  boardMarkdown,
};
})();

// ---- src/core/diff.js --------------------------------------------------------
const __iluboard_src_core_diff = (() => {
const { CARD_KEYS, cardsIn } = __iluboard_src_core_model;
const { columnLabel, cardLine } = __iluboard_src_core_text;
// What changed between two versions of a board: cards moved between columns,
// added, removed, edited; columns reordered inside; meta and columns changes.
// Pure module.


// `order` shows up as reordering; `updated` / `updated_by` change with every edit.
const IGNORED = new Set(['id', 'column', 'order', 'updated', 'updated_by']);

const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const cardsOf = (doc) => (Array.isArray(doc?.cards) ? doc.cards.filter((c) => c && typeof c.id === 'string') : []);

/**
 * Compare boards `a` (before) and `b` (after).
 * { moved: [{id, title, from, to, by}], added: [card], removed: [card],
 *   changed: [{id, title, by, fields: [{key, from, to}]}], reordered: [column],
 *   meta: [{key, from, to}], columns: {from, to} | null, empty: boolean }
 */
function diffBoards(a, b) {
  const before = new Map(cardsOf(a).map((c) => [c.id, c]));
  const after = new Map(cardsOf(b).map((c) => [c.id, c]));
  const moved = [];
  const added = [];
  const removed = [];
  const changed = [];

  for (const [id, c] of after) {
    const old = before.get(id);
    if (!old) { added.push(c); continue; }
    if (old.column !== c.column) moved.push({ id, title: c.title, from: old.column, to: c.column, by: c.updated_by });
    const keys = [...new Set([...CARD_KEYS, ...Object.keys(old), ...Object.keys(c)])].filter((k) => !IGNORED.has(k));
    const fields = keys.filter((k) => !same(old[k], c[k])).map((k) => ({ key: k, from: old[k], to: c[k] }));
    if (fields.length) changed.push({ id, title: c.title, by: c.updated_by, fields });
  }
  for (const [id, c] of before) if (!after.has(id)) removed.push(c);

  // Reordered columns: the relative order of cards that were in the column before and after differs.
  const reordered = [];
  const colsB = Array.isArray(b?.columns) ? b.columns : [];
  for (const col of colsB) {
    const was = safeCardsIn(a, col).map((c) => c.id);
    const now = safeCardsIn(b, col).map((c) => c.id);
    const common = new Set(was.filter((id) => now.includes(id)));
    const x = was.filter((id) => common.has(id));
    const y = now.filter((id) => common.has(id));
    if (!same(x, y)) reordered.push(col);
  }

  const meta = [];
  const ma = a?.meta || {};
  const mb = b?.meta || {};
  for (const k of [...new Set([...Object.keys(ma), ...Object.keys(mb)])]) {
    if (k !== 'updated' && !same(ma[k], mb[k])) meta.push({ key: k, from: ma[k], to: mb[k] });
  }
  const columns = same(a?.columns, b?.columns) ? null : { from: a?.columns, to: b?.columns };

  const empty = !moved.length && !added.length && !removed.length && !changed.length && !reordered.length && !meta.length && !columns;
  return { moved, added, removed, changed, reordered, meta, columns, empty };
}

function safeCardsIn(doc, col) {
  if (!Array.isArray(doc?.cards)) return [];
  return cardsIn({ cards: cardsOf(doc) }, col);
}

const DIFF_WORDS = {
  ru: {
    none: 'Изменений нет.', moved: 'Перенесены', added: 'Новые', removed: 'Удалены', changed: 'Изменены',
    reordered: 'Порядок изменён', meta: 'Доска', columns: 'Колонки', in: 'в', was: 'было', empty: 'пусто',
  },
  en: {
    none: 'No changes.', moved: 'Moved', added: 'Added', removed: 'Removed', changed: 'Changed',
    reordered: 'Reordered', meta: 'Board', columns: 'Columns', in: 'in', was: 'was', empty: 'empty',
  },
};

const short = (v, emptyWord) => {
  if (v === undefined || v === null || v === '' || (Array.isArray(v) && !v.length)) return `(${emptyWord})`;
  const s = Array.isArray(v) ? v.join(', ') : typeof v === 'object' ? JSON.stringify(v) : String(v);
  const one = s.replace(/\s*\n\s*/g, ' / ');
  return `"${one.length > 80 ? `${one.slice(0, 79)}…` : one}"`;
};

/** The diff as Markdown-ish text. */
function diffText(d, { lang = 'ru' } = {}) {
  const w = DIFF_WORDS[lang] || DIFF_WORDS.en;
  if (d.empty) return `${w.none}\n`;
  const out = [];
  const section = (title, lines) => {
    if (!lines.length) return;
    if (out.length) out.push('');
    out.push(`## ${title} (${lines.length})`, '', ...lines);
  };
  const col = (c) => columnLabel(c, lang);
  const by = (x) => (x ? ` · ${x}` : '');
  section(w.moved, d.moved.map((m) => `- ${m.id} ${m.title}: ${col(m.from)} → ${col(m.to)}${by(m.by)}`));
  section(w.added, d.added.map((c) => `- ${cardLine(c, lang)} — ${w.in} «${col(c.column)}»${by(c.updated_by)}`));
  section(w.removed, d.removed.map((c) => `- ${cardLine(c, lang)} — ${w.was} ${w.in} «${col(c.column)}»`));
  section(w.changed, d.changed.map((c) => `- ${c.id} ${c.title}${by(c.by)}: ${c.fields.map((f) => `${f.key} ${short(f.from, w.empty)} → ${short(f.to, w.empty)}`).join('; ')}`));
  if (d.reordered.length) section(w.reordered, [`- ${d.reordered.map(col).join(', ')}`]);
  const boardLines = d.meta.map((m) => `- meta.${m.key}: ${short(m.from, w.empty)} → ${short(m.to, w.empty)}`);
  if (d.columns) boardLines.push(`- ${w.columns}: ${(d.columns.from || []).join(', ')} → ${(d.columns.to || []).join(', ')}`);
  section(w.meta, boardLines);
  return `${out.join('\n')}\n`;
}

/** One short line: "2 moved, 1 added" — for toasts. */
function diffSummary(d, lang = 'ru') {
  const w = DIFF_WORDS[lang] || DIFF_WORDS.en;
  if (d.empty) return w.none.replace(/\.$/, '');
  const parts = [];
  if (d.moved.length) parts.push(`${w.moved.toLowerCase()}: ${d.moved.length}`);
  if (d.added.length) parts.push(`${w.added.toLowerCase()}: ${d.added.length}`);
  if (d.removed.length) parts.push(`${w.removed.toLowerCase()}: ${d.removed.length}`);
  if (d.changed.length) parts.push(`${w.changed.toLowerCase()}: ${d.changed.length}`);
  if (!parts.length && d.reordered.length) parts.push(w.reordered.toLowerCase());
  if (!parts.length) parts.push(w.meta.toLowerCase());
  return parts.join(', ');
}
return {
  diffBoards,
  diffText,
  diffSummary,
};
})();

// ---- tools/iluboard.mjs ------------------------------------------------------
const { readFileSync, writeFileSync, renameSync } = __node_fs;
const { basename, dirname, resolve } = __node_path;
const { execFileSync } = __node_child_process;
const { APP_VERSION } = __iluboard_src_core_version;
const { VERSION, EDITABLE_KEYS, emptyBoard, normalize, validate, issueText, serialize, findCard, moveCard, addCard, setFields, today } = __iluboard_src_core_model;
const { boardText, boardMarkdown, columnLabel } = __iluboard_src_core_text;
const { diffBoards, diffText } = __iluboard_src_core_diff;
// IluBoard CLI — read, check, describe and edit board.json without a browser.
// Source of the single-file bundle `iluboard.mjs` (npm run bundle).
//
//   node tools/iluboard.mjs --help


const HELP = `IluBoard ${APP_VERSION} — kanban board in one JSON file (board format v${VERSION})

Usage: node iluboard.mjs <command> <board.json> [options]

Read
  text <file> [--full] [--columns todo,doing]   the board as text, one line per card
  md <file> [--out backlog.md] [--columns ...]   Markdown tables (for backlog.md)
  validate <file> [--json]                       schema, unique ids, columns, done_when; exit 1 on errors
  diff <file> --git [rev]                        what changed since the last commit (default HEAD)
  diff <old.json> <new.json>                     what changed between two files
       [--json]

Write (re-read → change → validate → write canonical file; nothing is written when invalid)
  fmt <file> [--check]                           canonical format (key order, cards by column and order)
  move <file> <id> <column> [--top | --index N] [--done-when "…"]
  add <file> --title "…" [--id B9] [--column todo] [--priority P1] [--size M]
       [--owner max] [--goal 3b] [--done-when "…"] [--notes "…"] [--tags a,b]
       [--due 2026-10-12] [--top]
  set <file> <id> [--title "…"] [--priority P0] …  change fields ("" removes a field)
  init <file> [--title "Project"] [--prefix B]   create an empty board (refuses to overwrite)

Options
  --lang ru|en      language of text / md / diff / messages (default ru, or ILUBOARD_LANG)
  --by agent|human  who is recorded in updated_by (default agent)
  --version, --help

Columns: idea, todo, doing, done, dropped (from the file). todo and doing need done_when.
Docs: https://ilumetric.github.io/IluBoard/docs/AGENT.md
`;

const BOOL = new Set(['full', 'check', 'json', 'top', 'help', 'version', 'h', 'v', 'force']);

function parseArgs(argv) {
  const pos = [];
  const opt = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--') { pos.push(...argv.slice(i + 1)); break; }
    if (a.startsWith('--') || /^-[a-z]$/.test(a)) {
      let key = a.replace(/^--?/, '');
      let val;
      const eq = key.indexOf('=');
      if (eq >= 0) { val = key.slice(eq + 1); key = key.slice(0, eq); }
      key = key.replace(/-/g, '_');
      if (val === undefined) {
        if (BOOL.has(key)) val = true;
        else if (key === 'git') val = argv[i + 1] && !argv[i + 1].startsWith('-') && !/\.json$/i.test(argv[i + 1]) ? argv[++i] : 'HEAD';
        else if (i + 1 < argv.length) val = argv[++i];
        else throw new UsageError(`option --${key} needs a value`);
      }
      opt[key] = val;
    } else pos.push(a);
  }
  return { pos, opt };
}

class UsageError extends Error {}

const out = (s) => process.stdout.write(s.endsWith('\n') ? s : `${s}\n`);
const err = (s) => process.stderr.write(s.endsWith('\n') ? s : `${s}\n`);

function readBoard(file) {
  let text;
  try { text = readFileSync(file, 'utf8'); } catch (e) {
    throw new UsageError(e.code === 'ENOENT' ? `${file}: no such file` : `${file}: ${e.message}`);
  }
  try { return { text, doc: normalize(text) }; } catch (e) { throw new UsageError(`${file}: ${e.message}`); }
}

/** Validate and write atomically; returns false (and prints why) when invalid. */
function writeBoard(file, doc, lang, { touchMeta = true } = {}) {
  if (touchMeta && doc.meta && typeof doc.meta === 'object') doc.meta.updated = today();
  const v = validate(doc);
  if (!v.ok) {
    err(`${file}: not written — the board would be invalid:`);
    for (const e of v.errors) err(`  error: ${issueText(e, lang)}`);
    return false;
  }
  const tmp = `${file}.${process.pid}.tmp`;
  writeFileSync(tmp, serialize(doc), 'utf8');
  renameSync(tmp, file);
  return true;
}

/** Card fields from options (--done-when → done_when). */
function fieldsFrom(opt) {
  const f = {};
  for (const k of EDITABLE_KEYS) if (opt[k] !== undefined && opt[k] !== true) f[k] = String(opt[k]);
  for (const k of Object.keys(opt)) if (k.startsWith('x_')) f[k] = opt[k];
  return f;
}

function gitVersion(file, rev) {
  const dir = dirname(resolve(file));
  try {
    execFileSync('git', ['-C', dir, 'rev-parse', '--is-inside-work-tree'], { stdio: ['ignore', 'pipe', 'pipe'] });
  } catch {
    throw new UsageError(`${file}: not inside a git repository`);
  }
  try {
    return execFileSync('git', ['-C', dir, 'show', `${rev}:./${basename(file)}`], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 64 * 1024 * 1024 });
  } catch {
    return null; // not in that revision (new file)
  }
}

const COMMANDS = {
  text({ pos, opt, lang }) {
    const { doc } = readBoard(need(pos[0], 'file'));
    out(boardText(doc, { lang, full: !!opt.full, columns: list(opt.columns) }));
  },

  md({ pos, opt, lang }) {
    const file = need(pos[0], 'file');
    const { doc } = readBoard(file);
    const text = boardMarkdown(doc, { lang, columns: list(opt.columns), source: basename(file) });
    if (opt.out) { writeFileSync(opt.out, text, 'utf8'); out(`wrote ${opt.out}`); } else out(text);
  },

  validate({ pos, opt, lang }) {
    const file = need(pos[0], 'file');
    const { doc } = readBoard(file);
    const v = validate(doc);
    if (opt.json) {
      out(JSON.stringify({ ok: v.ok, errors: v.errors.map((e) => ({ ...e, message: issueText(e, lang) })), warnings: v.warnings.map((e) => ({ ...e, message: issueText(e, lang) })) }, null, 2));
      return v.ok ? 0 : 1;
    }
    for (const e of v.errors) out(`error: ${issueText(e, lang)}  [${e.path}]`);
    for (const w of v.warnings) out(`warning: ${issueText(w, lang)}  [${w.path}]`);
    out(v.ok ? `${file}: ok (${doc.cards.length} cards${v.warnings.length ? `, ${v.warnings.length} warnings` : ''})` : `${file}: ${v.errors.length} error(s)`);
    return v.ok ? 0 : 1;
  },

  fmt({ pos, opt }) {
    const file = need(pos[0], 'file');
    const { text, doc } = readBoard(file);
    const canon = serialize(doc);
    if (opt.check) {
      out(canon === text ? `${file}: canonical` : `${file}: not canonical (run: node iluboard.mjs fmt ${file})`);
      return canon === text ? 0 : 1;
    }
    if (canon === text) { out(`${file}: already canonical`); return 0; }
    writeFileSync(file, canon, 'utf8');
    out(`${file}: formatted`);
    return 0;
  },

  diff({ pos, opt, lang }) {
    let a;
    let b;
    let note = '';
    if (opt.git) {
      const file = need(pos[0], 'file');
      b = readBoard(file).doc;
      const old = gitVersion(file, opt.git);
      if (old === null) { a = emptyBoard(); a.columns = b.columns; note = `${file} is not in ${opt.git}: every card is new.\n\n`; } else a = normalize(old);
    } else {
      if (pos.length < 2) throw new UsageError('diff needs two files, or one file and --git [rev]');
      a = readBoard(pos[0]).doc;
      b = readBoard(pos[1]).doc;
    }
    const d = diffBoards(a, b);
    if (opt.json) out(JSON.stringify(d, null, 2));
    else out(note + diffText(d, { lang }));
    return 0;
  },

  move({ pos, opt, lang, by }) {
    const file = need(pos[0], 'file');
    const id = need(pos[1], 'card id');
    const column = need(pos[2], 'column');
    const { doc } = readBoard(file);
    if (!findCard(doc, id)) throw new UsageError(`no card "${id}"`);
    if (!doc.columns.includes(column)) throw new UsageError(`no column "${column}" (columns: ${doc.columns.join(', ')})`);
    if (opt.done_when !== undefined) setFields(doc, id, { done_when: String(opt.done_when) }, { by });
    const index = opt.top ? 0 : opt.index !== undefined ? Number(opt.index) : undefined;
    const card = moveCard(doc, id, column, index, { by });
    if (!writeBoard(file, doc, lang)) return 1;
    out(`${card.id} → ${column} (${columnLabel(column, lang)}), position ${card.order}`);
    return 0;
  },

  add({ pos, opt, lang, by }) {
    const file = need(pos[0], 'file');
    const { doc } = readBoard(file);
    const fields = fieldsFrom(opt);
    if (!fields.title) throw new UsageError('add needs --title');
    let card;
    try {
      card = addCard(doc, { ...fields, id: opt.id, column: opt.column }, { by, index: opt.top ? 0 : undefined });
    } catch (e) { throw new UsageError(e.message); }
    if (!writeBoard(file, doc, lang)) return 1;
    out(`added ${card.id} → ${card.column} (${columnLabel(card.column, lang)})`);
    return 0;
  },

  set({ pos, opt, lang, by }) {
    const file = need(pos[0], 'file');
    const id = need(pos[1], 'card id');
    const { doc } = readBoard(file);
    if (!findCard(doc, id)) throw new UsageError(`no card "${id}"`);
    const fields = fieldsFrom(opt);
    if (!Object.keys(fields).length) throw new UsageError(`set needs at least one field (${EDITABLE_KEYS.map((k) => `--${k.replace(/_/g, '-')}`).join(' ')})`);
    const changed = setFields(doc, id, fields, { by });
    if (!changed.length) { out(`${id}: nothing changed`); return 0; }
    if (!writeBoard(file, doc, lang)) return 1;
    out(`${id}: ${changed.join(', ')}`);
    return 0;
  },

  init({ pos, opt }) {
    const file = need(pos[0], 'file');
    let exists = true;
    try { readFileSync(file); } catch { exists = false; }
    if (exists && !opt.force) throw new UsageError(`${file} already exists (use --force to overwrite)`);
    const doc = emptyBoard(opt.title ? String(opt.title) : 'Board');
    if (opt.prefix) doc.meta.id_prefix = String(opt.prefix);
    writeFileSync(file, serialize(doc), 'utf8');
    out(`created ${file}`);
    return 0;
  },
};

function need(v, what) {
  if (v === undefined) throw new UsageError(`missing ${what}`);
  return v;
}

const list = (v) => (typeof v === 'string' ? v.split(',').map((s) => s.trim()).filter(Boolean) : undefined);

function main(argv) {
  let args;
  try { args = parseArgs(argv); } catch (e) { err(`iluboard: ${e.message}`); return 2; }
  const { pos, opt } = args;
  if (opt.version || opt.v || pos[0] === 'version') { out(`iluboard ${APP_VERSION} (board format v${VERSION})`); return 0; }
  const cmd = pos.shift();
  if (!cmd || opt.help || opt.h || cmd === 'help') { out(HELP); return cmd || opt.help || opt.h ? 0 : 2; }
  const run = COMMANDS[cmd];
  if (!run) { err(`iluboard: unknown command "${cmd}" (see --help)`); return 2; }
  const lang = String(opt.lang || process.env.ILUBOARD_LANG || 'ru') === 'en' ? 'en' : 'ru';
  const by = opt.by === 'human' ? 'human' : 'agent';
  try {
    return run({ pos, opt, lang, by }) ?? 0;
  } catch (e) {
    if (e instanceof UsageError || e instanceof SyntaxError) { err(`iluboard: ${e.message}`); return 2; }
    throw e;
  }
}

process.exitCode = main(process.argv.slice(2));
